name: Android
on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm ci

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Android
        run: npm run android

      - name: Build Windows
        run: npm run dist

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'android'
          prerelease: false
          title: 'Android'
          files: |
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
